In [1]:
from google.colab import drive
drive.mount('/content/drive')

from pathlib import Path

#project folder
ROOT = Path('/content/drive/MyDrive/LSDDA')
RAW = ROOT      #CSV is directly inside LSDDA
PROC = ROOT / 'Processed'

#create processed folder if missing
PROC.mkdir(parents=True, exist_ok=True)

print("ROOT:", ROOT)
print("RAW :", RAW)
print("PROC:", PROC)

Mounted at /content/drive
ROOT: /content/drive/MyDrive/LSDDA
RAW : /content/drive/MyDrive/LSDDA
PROC: /content/drive/MyDrive/LSDDA/Processed

In [ ]:
from pathlib import Path
CSV_Path = RAW / 'CarSales_Dataset.csv'

if CSV_Path.exists():
  print('CSV found at:', CSV_Path)
else:
  raise FileNotFoundError("CSV NOT FOUND!")

CSV found at: /content/drive/MyDrive/LSDDA/CarSales_Dataset.csv

In [ ]:
import pandas as pd
df = pd.read_csv(CSV_Path)
print("Shape:", df.shape)
df.head(10)

Shape: (99817, 22)

,CarID,Manufacturer,Model,Engine size,Features,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerName,...,Longitude,ServiceID,Date_of_Service,ServiceType,Cost_of_Service,AccidentID,Date_of_Accident,Description,Cost_of_Repair,Severity
0,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
1,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
2,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
3,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
4,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
5,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
6,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
7,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
8,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
9,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe

In [ ]:
#remove duplicates
df_clean = df.drop_duplicates().copy()
print("original rows:", len(df))
print("after removing duplicates:", len(df_clean))
df_clean.head(10)

original rows: 99817
after removing duplicates: 99817

,CarID,Manufacturer,Model,Engine size,Features,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerName,...,Longitude,ServiceID,Date_of_Service,ServiceType,Cost_of_Service,AccidentID,Date_of_Accident,Description,Cost_of_Repair,Severity
0,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
1,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
2,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
3,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
4,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
5,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
6,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
7,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
8,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
9,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe

In [ ]:
#find all string (object) columns
str_cols = df_clean.select_dtypes(include='object').columns

#strip spaces from each
df_clean[str_cols] = df_clean[str_cols].apply(lambda col: col.str.strip())

print("trimmed space in:", len(str_cols), "columns")
df_clean.head(10)

trimmed space in: 14 columns

,CarID,Manufacturer,Model,Engine size,Features,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerName,...,Longitude,ServiceID,Date_of_Service,ServiceType,Cost_of_Service,AccidentID,Date_of_Accident,Description,Cost_of_Repair,Severity
0,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
1,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50378,25/02/2025,Front-end collision,715.0,Major
2,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
3,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,23/05/2024,Major Service,418.0,A50379,01/01/2023,Windshield damage,4914.0,Severe
4,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
5,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
6,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14186,05/12/2022,Minor fender bender,4469.0,Moderate
7,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
8,C09428,Ford,Focus,1.8,Bluetooth,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe
9,C09428,Ford,Focus,1.8,Cruise Control,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,-0.589500,NaN,NaN,NaN,NaN,A14187,04/04/2023,Door dent from tight parking,3468.0,Severe

In [ ]:
df_clean.dtypes

CarID                     object
Manufacturer              object
Model                     object
Engine size              float64
Features                  object
Fuel_Type                 object
Year_of_Manufacturing      int64
Mileage                    int64
Price                      int64
DealerName                object
DealerCity                object
Latitude                 float64
Longitude                float64
ServiceID                 object
Date_of_Service           object
ServiceType               object
Cost_of_Service          float64
AccidentID                object
Date_of_Accident          object
Description               object
Cost_of_Repair           float64
Severity                  object
dtype: object

In [ ]:
#convert numeric columns to numbers
# ALL numeric columns
numeric_cols = [
    "Mileage",
    "Price",
    "Cost_of_Service",
    "Cost_of_Repair",
    "Latitude",
    "Longitude",
    "Year_of_Manufacturing",
    "Engine size"
]

for col in numeric_cols:
    if col in df_clean.columns:
        df_clean[col] = pd.to_numeric(df_clean[col], errors="coerce")

df_clean[numeric_cols].head()

,Mileage,Price,Cost_of_Service,Cost_of_Repair,Latitude,Longitude,Year_of_Manufacturing,Engine size
0,21317,68597,418.0,715.0,53.713263,0.738007,2020,2.4
1,21317,68597,418.0,715.0,53.713263,0.738007,2020,2.4
2,21317,68597,418.0,4914.0,53.713263,0.738007,2020,2.4
3,21317,68597,418.0,4914.0,53.713263,0.738007,2020,2.4
4,22500,35276,NaN,4469.0,53.314723,-0.589500,2018,1.8

In [ ]:
df["Date_of_Service"].unique()[:50]

array(['23/05/2024', nan, '21/02/2025', '09/12/2022', '01/06/2022',
       '18/02/2021', '26/09/2022', '12/10/2020', '20/08/2025',
       '30/07/2022', '04/04/2025', '11/06/2024', '03/09/2020',
       '16/04/2023', '02/02/2021', '12/08/2021', '07/04/2024',
       '23/06/2025', '12/06/2024', '14/04/2025', '30/10/2024',
       '25/09/2023', '28/05/2022', '03/04/2022', '20/09/2024',
       '29/07/2024', '05/07/2023', '15/06/2025', '10/11/2021',
       '19/10/2022', '26/03/2023', '20/04/2021', '26/10/2020',
       '01/01/2024', '23/08/2023', '30/08/2025', '25/02/2023',
       '23/11/2020', '05/04/2025', '28/02/2025', '02/08/2025',
       '02/01/2021', '27/11/2022', '26/03/2025', '12/11/2024',
       '11/09/2020', '29/01/2025', '29/09/2021', '06/01/2022',
       '11/08/2021'], dtype=object)

In [ ]:
df["Date_of_Accident"].unique()[:50]

array(['25/02/2025', '01/01/2023', '05/12/2022', '04/04/2023',
       '14/12/2023', '09/05/2025', nan, '19/03/2025', '13/03/2025',
       '18/02/2021', '30/05/2021', '23/10/2022', '29/01/2025',
       '19/02/2023', '03/04/2023', '23/07/2023', '24/01/2022',
       '28/07/2023', '24/03/2022', '20/02/2025', '28/10/2024',
       '17/02/2025', '07/06/2021', '06/12/2023', '06/08/2024',
       '08/01/2021', '14/01/2025', '15/05/2023', '24/11/2023',
       '24/07/2022', '01/11/2022', '09/05/2021', '18/03/2025',
       '25/03/2024', '03/03/2021', '13/10/2020', '16/01/2022',
       '01/09/2020', '20/02/2023', '17/02/2022', '11/11/2020',
       '29/03/2024', '14/01/2024', '18/12/2023', '02/01/2025',
       '04/01/2023', '06/09/2024', '25/08/2022', '26/02/2022',
       '29/06/2024'], dtype=object)

In [ ]:
df.columns

Index(['CarID', 'Manufacturer', 'Model', 'Engine size', 'Features',
       'Fuel_Type', 'Year_of_Manufacturing', 'Mileage', 'Price', 'DealerName',
       'DealerCity', 'Latitude', 'Longitude', 'ServiceID', 'Date_of_Service',
       'ServiceType', 'Cost_of_Service', 'AccidentID', 'Date_of_Accident',
       'Description', 'Cost_of_Repair', 'Severity'],
      dtype='object')

In [ ]:
#clean up the date columns
date_cols = ["Date_of_Service", "Date_of_Accident"]

for col in date_cols:
    df_clean[col] = pd.to_datetime(
        df_clean[col],
        format="%d/%m/%Y",
        errors="coerce"
    ).dt.strftime("%Y-%m-%d")

df_clean[date_cols].head(20)

   Date_of_Service Date_of_Accident
0       2024-05-23       2025-02-25
1       2024-05-23       2025-02-25
2       2024-05-23       2023-01-01
3       2024-05-23       2023-01-01
4              NaN       2022-12-05
5              NaN       2022-12-05
6              NaN       2022-12-05
7              NaN       2023-04-04
8              NaN       2023-04-04
9              NaN       2023-04-04
10             NaN       2023-12-14
11             NaN       2023-12-14
12             NaN       2023-12-14
13             NaN       2023-12-14
14             NaN       2025-05-09
15             NaN       2025-05-09
16             NaN       2025-05-09
17             NaN       2025-05-09
18             NaN              NaN
19      2025-02-21       2025-03-19

In [ ]:
#data exploration

In [ ]:
df_clean.isna().sum()

CarID                        0
Manufacturer                 0
Model                        0
Engine size                  0
Features                     0
Fuel_Type                    0
Year_of_Manufacturing        0
Mileage                      0
Price                        0
DealerName                   0
DealerCity                   0
Latitude                     0
Longitude                    0
ServiceID                20927
Date_of_Service          20927
ServiceType              20927
Cost_of_Service          20927
AccidentID               14009
Date_of_Accident         14009
Description              14009
Cost_of_Repair           14009
Severity                 14009
dtype: int64

In [ ]:
df_clean.nunique()

CarID                    15000
Manufacturer                 5
Model                       15
Engine size                 14
Features                     6
Fuel_Type                    3
Year_of_Manufacturing       39
Mileage                  14509
Price                    11357
DealerName                  50
DealerCity                  36
Latitude                    50
Longitude                   50
ServiceID                17977
Date_of_Service           1826
ServiceType                 12
Cost_of_Service            451
AccidentID               22707
Date_of_Accident          1827
Description                 22
Cost_of_Repair            4857
Severity                     4
dtype: int64

In [ ]:
#overview of shape and columns
print("Shape of cleaned dataset:", df_clean.shape)
df_clean.info()

Shape of cleaned dataset: (99817, 22)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99817 entries, 0 to 99816
Data columns (total 22 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   CarID                  99817 non-null  object
 1   Manufacturer           99817 non-null  object
 2   Model                  99817 non-null  object
 3   Engine size            99817 non-null  float64
 4   Features               99817 non-null  object
 5   Fuel_Type              99817 non-null  object
 6   Year_of_Manufacturing  99817 non-null  int64
 7   Mileage                99817 non-null  int64
 8   Price                  99817 non-null  int64
 9   DealerName             99817 non-null  object
 10  DealerCity             99817 non-null  object
 11  Latitude               99817 non-null  float64
 12  Longitude              99817 non-null  float64
 13  ServiceID              78890 non-null  object
 14  Date_of_Service        78890 non-null  object
 15  ServiceType            78890 non-null  object
 16  Cost_of_Service        78890 non-null  float64
 17  AccidentID             85808 non-null  object
 18  Date_of_Accident       85808 non-null  object
 19  Description            85808 non-null  object
 20  Cost_of_Repair         85808 non-null  float64
 21  Severity               85808 non-null  object
dtypes: float64(5), int64(3), object(14)
memory usage: 16.8+ MB

In [ ]:
#count missing values
df_clean.isna().sum().sort_values(ascending=False)

Cost_of_Service          20927
ServiceID                20927
Date_of_Service          20927
ServiceType              20927
Cost_of_Repair           14009
AccidentID               14009
Severity                 14009
Date_of_Accident         14009
Description              14009
Features                     0
Manufacturer                 0
CarID                        0
Engine size                  0
Model                        0
Fuel_Type                    0
Longitude                    0
DealerCity                   0
Latitude                     0
Mileage                      0
Price                        0
Year_of_Manufacturing        0
DealerName                   0
dtype: int64

In [ ]:
#basic statistics
df_clean.describe()

,Engine size,Year_of_Manufacturing,Mileage,Price,Latitude,Longitude,Cost_of_Service,Cost_of_Repair
count,99817.000000,99817.000000,99817.000000,99817.000000,99817.000000,99817.000000,78890.000000,85808.000000
mean,1.781381,2004.189817,113543.146107,13794.031969,52.563686,-0.864933,274.608113,2543.834538
std,0.729423,9.620923,71759.597790,16326.661540,1.289489,1.174179,130.296264,1416.842397
min,1.000000,1984.000000,1000.000000,76.000000,50.054503,-2.996212,50.000000,100.000000
25%,1.400000,1996.000000,56084.000000,3082.000000,51.343937,-1.856727,160.000000,1316.000000
50%,1.600000,2004.000000,102105.000000,7981.000000,52.615955,-0.921661,275.000000,2536.000000
75%,2.000000,2012.000000,159371.000000,18997.000000,53.356850,0.179480,387.000000,3770.000000
max,5.000000,2022.000000,446897.000000,167774.000000,54.966148,0.912489,500.000000,5000.000000

In [ ]:
#uniqueness
print("Unique CarIDs:", df_clean["CarID"].nunique())
print("Unique DealerNames:", df_clean["DealerName"].nunique())
print("Unique ServiceIDs:", df_clean["ServiceID"].nunique())
print("Unique AccidentIDs:", df_clean["AccidentID"].nunique())

Unique CarIDs: 15000
Unique DealerNames: 50
Unique ServiceIDs: 17977
Unique AccidentIDs: 22707

In [ ]:
#common features
df_clean["Features"].value_counts().head(10)

Features
Sunroof             16798
Heated Seats        16707
Navigation          16693
Bluetooth           16570
Cruise Control      16539
Air Conditioning    16510
Name: count, dtype: int64

In [ ]:
#common manufacturers
df_clean["Manufacturer"].value_counts().head(10)

Manufacturer
VW         30048
Ford       28887
Toyota     25670
BMW         9948
Porsche     5264
Name: count, dtype: int64

In [ ]:
#cars with multiple services and/or features
sample_car = df_clean["CarID"].iloc[0]
df_clean[df_clean["CarID"] == sample_car].head(20)

,CarID,Manufacturer,Model,Engine size,Features,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerName,...,Longitude,ServiceID,Date_of_Service,ServiceType,Cost_of_Service,AccidentID,Date_of_Accident,Description,Cost_of_Repair,Severity
0,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,2024-05-23,Major Service,418.0,A50378,2025-02-25,Front-end collision,715.0,Major
1,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,2024-05-23,Major Service,418.0,A50378,2025-02-25,Front-end collision,715.0,Major
2,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,2024-05-23,Major Service,418.0,A50379,2023-01-01,Windshield damage,4914.0,Severe
3,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,0.738007,S100854,2024-05-23,Major Service,418.0,A50379,2023-01-01,Windshield damage,4914.0,Severe

In [ ]:
#accidents vs no accidents
acc_count = df_clean["AccidentID"].notna().sum()
acc_none = df_clean["AccidentID"].isna().sum()

print("Rows WITH accidents:", acc_count)
print("Rows WITHOUT accidents:", acc_none)

Rows WITH accidents: 85808
Rows WITHOUT accidents: 14009

In [ ]:
cars_with_accidents = df_clean.dropna(subset=["AccidentID"])["CarID"].nunique()
cars_total = df_clean["CarID"].nunique()

print("Cars with ≥1 accident:", cars_with_accidents)
print("Total cars:", cars_total)
print("Percentage:", round(100 * cars_with_accidents / cars_total, 2), "%")

Cars with ≥1 accident: 11308
Total cars: 15000
Percentage: 75.39 %

In [ ]:
df_clean.shape

(99817, 22)

In [ ]:
#begin to split the dataset

In [ ]:
#create the dealer table
dealer_cols = ["DealerName", "DealerCity", "Longitude", "Latitude"]

#extract unique dealer
dealer_df = (
    df_clean[dealer_cols]
    .drop_duplicates()
    .reset_index(drop=True)
)
#create DealerID (PK)
dealer_df.insert(0, "DealerID", range(1, len(dealer_df) + 1))

#save table
Dealer_File = PROC / "Dealer.csv"
dealer_df.to_csv(Dealer_File, index=False)

dealer_df.head()
dealer_df.shape

(50, 5)

In [ ]:
#compare to original
print("Unique dealers in original df_clean :", df_clean['DealerName'].nunique())
print("Unique dealers in dealer_df        :", dealer_df['DealerName'].nunique())

Unique dealers in original df_clean : 50
Unique dealers in dealer_df        : 50

In [ ]:
#merge DealerID to the original dataset
df_merged = df_clean.merge(
    dealer_df,
    on=["DealerName", "DealerCity", "Latitude", "Longitude"],
    how="left",
    validate="m:1"
)

df_merged.head()

,CarID,Manufacturer,Model,Engine size,Features,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerName,...,ServiceID,Date_of_Service,ServiceType,Cost_of_Service,AccidentID,Date_of_Accident,Description,Cost_of_Repair,Severity,DealerID
0,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,S100854,2024-05-23,Major Service,418.0,A50378,2025-02-25,Front-end collision,715.0,Major,1
1,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,S100854,2024-05-23,Major Service,418.0,A50378,2025-02-25,Front-end collision,715.0,Major,1
2,C33554,Toyota,RAV4,2.4,Heated Seats,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,S100854,2024-05-23,Major Service,418.0,A50379,2023-01-01,Windshield damage,4914.0,Severe,1
3,C33554,Toyota,RAV4,2.4,Bluetooth,Hybrid,2020,21317,68597,"Proctor, Villarreal and Hurley",...,S100854,2024-05-23,Major Service,418.0,A50379,2023-01-01,Windshield damage,4914.0,Severe,1
4,C09428,Ford,Focus,1.8,Heated Seats,Petrol,2018,22500,35276,"Walker, Baxter and Daniel",...,NaN,NaN,NaN,NaN,A14186,2022-12-05,Minor fender bender,4469.0,Moderate,2

In [ ]:
#build the car table
car_cols = [
    "CarID",
    "Manufacturer",
    "Model",
    "Engine size",
    "Fuel_Type",
    "Year_of_Manufacturing",
    "Mileage",
    "Price",
    "DealerID"
]

car_df = (
    df_merged[car_cols]
    .drop_duplicates()
    .reset_index(drop=True)
)

CAR_FILE = PROC / "Car.csv"
car_df.to_csv(CAR_FILE, index=False)

car_df.head()
car_df.shape

(15000, 9)

In [ ]:
#compare to original
print("Unique CarIDs in original df_clean:", df_clean["CarID"].nunique())
print("Unique CarIDs in car_df          :", car_df["CarID"].nunique())

car_df.head()

Unique CarIDs in original df_clean: 15000
Unique CarIDs in car_df          : 15000

,CarID,Manufacturer,Model,Engine size,Fuel_Type,Year_of_Manufacturing,Mileage,Price,DealerID
0,C33554,Toyota,RAV4,2.4,Hybrid,2020,21317,68597,1
1,C09428,Ford,Focus,1.8,Petrol,2018,22500,35276,2
2,C00200,Ford,Mondeo,1.6,Diesel,2013,79521,17370,3
3,C12448,Toyota,Yaris,1.2,Petrol,2003,159534,3213,4
4,C39490,Ford,Mondeo,1.4,Diesel,2000,126511,4832,5

In [ ]:
#ensure dealer ids are unique + not regenerated
df_merged.groupby("DealerName")["DealerID"].nunique().sort_values(ascending=False).head(10)

DealerName
Adams-Kelly                 1
Aguilar LLC                 1
Allen-Jones                 1
Anderson-Rivas              1
Bailey, Grant and Carter    1
Black, Black and Bishop     1
Brewer-Sosa                 1
Brooks, Thomas and Davis    1
Brown Group                 1
Brown Inc                   1
Name: DealerID, dtype: int64

In [ ]:
df_merged[["DealerName", "DealerCity", "DealerID"]].drop_duplicates().head(20)

                         DealerName           DealerCity  DealerID
0    Proctor, Villarreal and Hurley           Gloucester         1
4         Walker, Baxter and Daniel             Brighton         2
10                  Ingram-Mitchell               Durham         3
14                   Sandoval Group             Bradford         4
18         Wagner, Cobb and Jenkins  Newcastle upon Tyne         5
33                     Warner-Payne            Cambridge         6
35                      Brown Group             Bradford         7
47         Simmons, Fields and Wolf               London         8
50                    Mclean-Miller                 Bath         9
56                        Smith LLC           Chelmsford        10
58                        Carr-Shaw               Woking        11
68                      Cruz-Castro        Wolverhampton        12
92                        Smith Ltd               Exeter        13
94         Bailey, Grant and Carter           Sunderland        14
107                  Vasquez-Murphy              Watford        15
125                  Johnson-Turner        Milton Keynes        16
138                     Aguilar LLC           Birmingham        17
144                   Turner-Walton              Norwich        18
148     Davis, Guerrero and Vasquez           Sunderland        19
150                 Wilson and Sons                 York        20

In [ ]:
print("DealerIDs in dealer_df:", dealer_df["DealerID"].nunique())
print("DealerIDs in car_df   :", car_df["DealerID"].nunique())

DealerIDs in dealer_df: 50
DealerIDs in car_df   : 50

In [ ]:
#create feature table
import pandas as pd
#extract unique features
feature_df = (
    df_merged[["Features"]]
    .dropna()                 #remove empty rows
    .drop_duplicates()        #keep only unique features
    .reset_index(drop=True)
)

#create FeatureID (Primary Key)
feature_df.insert(0, "FeatureID", range(1, len(feature_df) + 1))

#save feature table
FEATURE_FILE = PROC / "Feature.csv"
feature_df.to_csv(FEATURE_FILE, index=False)

feature_df.head(), feature_df.shape

(   FeatureID          Features
 0          1      Heated Seats
 1          2         Bluetooth
 2          3    Cruise Control
 3          4           Sunroof
 4          5  Air Conditioning,
 (6, 2))

In [ ]:
print("Unique features in original df_clean :", df_clean["Features"].nunique())
print("Unique features in feature_df       :", feature_df["Features"].nunique())

feature_df.head()

Unique features in original df_clean : 6
Unique features in feature_df       : 6

   FeatureID          Features
0          1      Heated Seats
1          2         Bluetooth
2          3    Cruise Control
3          4           Sunroof
4          5  Air Conditioning

In [ ]:
#build carfeature table

#join df_merged with feature_df to get FeatureID for each row
carfeature_df = (
    df_merged[["CarID", "Features"]]
    .dropna(subset=["Features"])            #keep rows with features
    .merge(feature_df, on="Features", how="left", validate="m:1")
    [["CarID", "FeatureID"]]
    .drop_duplicates()
    .reset_index(drop=True)
)

#save join table
CarFeature_File = PROC / "CarFeature.csv"
carfeature_df.to_csv(CarFeature_File, index=False)

carfeature_df.head(), carfeature_df.shape

(    CarID  FeatureID
 0  C33554          1
 1  C33554          2
 2  C09428          1
 3  C09428          2
 4  C09428          3,
 (37587, 2))

In [ ]:
#compare to original
print("Unique CarIDs in original:", df_clean["CarID"].nunique())
print("Unique CarIDs in CarFeature:", carfeature_df["CarID"].nunique())

print("\nUnique FeatureIDs in Feature table:", feature_df["FeatureID"].nunique())
print("Unique FeatureIDs in CarFeature:", carfeature_df["FeatureID"].nunique())

carfeature_df.head()

Unique CarIDs in original: 15000
Unique CarIDs in CarFeature: 15000

Unique FeatureIDs in Feature table: 6
Unique FeatureIDs in CarFeature: 6

    CarID  FeatureID
0  C33554          1
1  C33554          2
2  C09428          1
3  C09428          2
4  C09428          3

In [ ]:
service_cols = [
    "ServiceID",
    "CarID",
    "Date_of_Service",
    "ServiceType",
    "Cost_of_Service"
]

service_df = (
    df_merged[service_cols]
    .dropna(subset=["ServiceID"])        #only keep real service rows
    .drop_duplicates()
    .reset_index(drop=True)
)

Service_File = PROC / "Service.csv"
service_df.to_csv(Service_File, index=False)

service_df.head(), service_df.shape

(  ServiceID   CarID Date_of_Service             ServiceType  Cost_of_Service
 0   S100854  C33554      2024-05-23           Major Service            418.0
 1   S128315  C42725      2025-02-21  Air Filter Replacement            232.0
 2    S32674  C10823      2022-12-09        Suspension Check            114.0
 3    S32673  C10823      2022-06-01         Wheel Alignment            216.0
 4    S12470  C04145      2021-02-18  Air Filter Replacement            290.0,
 (17977, 5))

In [ ]:
print("Unique ServiceIDs in original df_clean:", df_clean["ServiceID"].nunique())
print("Unique ServiceIDs in service_df      :", service_df["ServiceID"].nunique())

print("\nDo all ServiceIDs link to valid CarIDs?")
print(service_df["CarID"].isin(car_df["CarID"]).all())

print("\nMissing CarIDs in service table:", service_df["CarID"].isna().sum())
service_df.head()

Unique ServiceIDs in original df_clean: 17977
Unique ServiceIDs in service_df      : 17977

Do all ServiceIDs link to valid CarIDs?
True

Missing CarIDs in service table: 0

  ServiceID   CarID Date_of_Service             ServiceType  Cost_of_Service
0   S100854  C33554      2024-05-23           Major Service            418.0
1   S128315  C42725      2025-02-21  Air Filter Replacement            232.0
2    S32674  C10823      2022-12-09        Suspension Check            114.0
3    S32673  C10823      2022-06-01         Wheel Alignment            216.0
4    S12470  C04145      2021-02-18  Air Filter Replacement            290.0

In [ ]:
accident_cols = [
    "AccidentID",
    "CarID",
    "Date_of_Accident",
    "Description",
    "Cost_of_Repair",
    "Severity"
]

accident_df = (
    df_merged[accident_cols]
    .dropna(subset=["AccidentID"])         #keep ONLY real accident rows
    .drop_duplicates()
    .reset_index(drop=True)
)

Accident_File = PROC / "Accident.csv"
accident_df.to_csv(Accident_File, index=False)

accident_df.head(), accident_df.shape

(  AccidentID   CarID Date_of_Accident                   Description  \
 0     A50378  C33554       2025-02-25           Front-end collision
 1     A50379  C33554       2023-01-01             Windshield damage
 2     A14186  C09428       2022-12-05           Minor fender bender
 3     A14187  C09428       2023-04-04  Door dent from tight parking
 4     A00295  C00200       2023-12-14           Front bumper scrape

    Cost_of_Repair  Severity
 0           715.0     Major
 1          4914.0    Severe
 2          4469.0  Moderate
 3          3468.0    Severe
 4          2625.0  Moderate  ,
 (22707, 6))

In [ ]:
print("Unique AccidentIDs in original df_clean:", df_clean["AccidentID"].nunique())
print("Unique AccidentIDs in accident_df      :", accident_df["AccidentID"].nunique())

print("\nDo all AccidentIDs link to valid CarIDs?")
print(accident_df["CarID"].isin(car_df["CarID"]).all())

print("\nMissing CarIDs in accident table:", accident_df["CarID"].isna().sum())
accident_df.head()

Unique AccidentIDs in original df_clean: 22707
Unique AccidentIDs in accident_df      : 22707

Do all AccidentIDs link to valid CarIDs?
True

Missing CarIDs in accident table: 0

,AccidentID,CarID,Date_of_Accident,Description,Cost_of_Repair,Severity
0,A50378,C33554,2025-02-25,Front-end collision,715.0,Major
1,A50379,C33554,2023-01-01,Windshield damage,4914.0,Severe
2,A14186,C09428,2022-12-05,Minor fender bender,4469.0,Moderate
3,A14187,C09428,2023-04-04,Door dent from tight parking,3468.0,Severe
4,A00295,C00200,2023-12-14,Front bumper scrape,2625.0,Moderate

In [ ]:
#final integrity check
print("1) CarIDs match:",
      df_clean["CarID"].nunique() == car_df["CarID"].nunique())

print("2) DealerIDs valid:",
      set(car_df["DealerID"]).issubset(set(dealer_df["DealerID"])))

print("3) Service + Accident CarIDs valid:",
      service_df["CarID"].isin(car_df["CarID"]).all() and
      accident_df["CarID"].isin(car_df["CarID"]).all())

1) CarIDs match: True
2) DealerIDs valid: True
3) Service + Accident CarIDs valid: True

In [ ]:
dealer_df.to_csv("/content/drive/MyDrive/LSDDA/Processed/Dealer_noheader.csv", index=False, header=False)

In [ ]:
#folder where your processed CSVs live
PROC = Path("/content/drive/MyDrive/LSDDA/Processed")

#save all tables WITHOUT HEADERS for SQL
car_df.to_csv(PROC / "Car_noheader.csv", index=False, header=False)
feature_df.to_csv(PROC / "Feature_noheader.csv", index=False, header=False)
carfeature_df.to_csv(PROC / "CarFeature_noheader.csv", index=False, header=False)
service_df.to_csv(PROC / "Service_noheader.csv", index=False, header=False)
accident_df.to_csv(PROC / "Accident_noheader.csv", index=False, header=False)

print("All no-header CSVs created successfully!")

All no-header CSVs created successfully!